### ISSUE TITLE
The DialogueGCN is great but how to extract the dataset feature. Actually I want to use my own dataset of similar format. Can please share the code or supporting material at yagyapandeyacbnu@gmail.com. Thanks.

### ISSUE THREAD

**Issue by pandeyapraj** [declare-lab/conv-emotion#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by soujanyaporia** [comment]
Please check this - https://github.com/declare-lab/conv-emotion/blob/master/DialogueGCN/preprocess_dailydialog.py
