### ISSUE TITLE
Can you share the Data Preprocessing Code of DialogueGCN for Dailydialogue dataset ?

### ISSUE THREAD

**Issue by RaleLee** [declare-lab/conv-emotion#38]
Hi, I'm working on your DialogueGCN model now. And I also learned DialogueRNN before. However, I found that the data preprecessor of DialogueRNN is a little bit different from DialogueGCN. 
The DialogueGCN needs parameter
```
def __init__(self, split, path):
        
        self.Speakers, self.Features, \
        self.ActLabels, self.EmotionLabels, self.trainId, self.testId, self.validId = pickle.load(open(path, 'rb')) 
```
And the DialogueRNN is like:
```
def __init__(self, split, path):
        
        self.Speakers, self.InputSequence, self.InputMaxSequenceLength, \
        self.ActLabels, self.EmotionLabels, self.trainId, self.testId, self.validId = pickle.load(open(path, 'rb'))
```
If I use the data preprocessor in DialogueRNN to preprocess Dailydialogue Dataset and get a pkl file. Then I use this pkl file in DialogueGCN. I get the Error below:
```
self.Speakers, self.Features, self.ActLabels, self.EmotionLabels, self.trainId, self.testId, self.validId = pickle.load(open(path, 'rb'))
ValueError: too many values to unpack (expected 7)
```
So it seems like i need a new data preprocessor of DialogueGCN for Dailydailogue dataset.
Thanks for help!

**Comment by soujanyaporia** [comment]
@deepanwayx, please help.

**Comment by deepanwayx** [comment]
In `DialogueGCN/dataloader.py` the `self.Features` is the CNN extracted utterance features vectors. We didn't extract those for DailyDialog. So you can follow one of the two methods below:

- Extract those features yourself following Section 3.2 in the DialogueGCN paper, put that in the pkl file and train the model similar to training the IEMOCAP model in `DialogueGCN/train_iemocap.py`. 

- Train the model end-to-end. You can have a look at the DailyDialogue model for DialogueRNN: [https://github.com/declare-lab/conv-emotion/blob/master/DialogueRNN/model.py#L586](url) to see how it can be done. The current DilogueGCN model takes as input the utterance level features, so you will need to add the `CNNFeatureExtractor` component for DailyDialogue and then use the graph model on top of that.

**Comment by RaleLee** [comment]
Well thanks for help! I followed the paper settings. I used glove.840B.300d.txt to preprocess the InputSequence and used CNN to extract features from 300-dimension vector to 100-dimension vector. Finally I got a good result on Dailydiaog Dataset. And I release this preprocessing code on https://github.com/RaleLee/DialogueGCN

**Comment by soujanyaporia** [comment]
Thats great! Could you please PR to our repo with your changes? We will definitely cite your work and give you proper credit. Let us know, please. Thank you!

**Comment by RaleLee** [comment]
Oh I'm very happy to do this. Please wait, I need refactor my code before PR to your repo.

**Comment by soujanyaporia** [comment]
Sure! Thanks a lot :)

**Comment by soujanyaporia** [comment]
Thanks!
