### ISSUE TITLE
label index mapping of MELD

### ISSUE THREAD

**Issue by hikaruya8** [declare-lab/conv-emotion#40]
In dataloader.py of DialougueRNN, label index mapping is written as comment out at MELD Dataset class. There are 6 labels.
```
label index mapping = {'hap':0, 'sad':1, 'neu':2, 'ang':3, 'exc':4, 'fru':5}
```
However, in the MELD paper, the annotated labels were these 7  which were
```
Joy, Sadness, Fear, Anger, Surprise, Disgust, Neutral
```

According to MELD repository, I think label index mapping is

{'neutral': 0, 'surprise': 1, 'fear': 2, 'sadness': 3, 'joy': 4, 'disgust': 5, 'anger': 6}.

If I am misunderstanding of MELD paper, I am sorry.

**Comment by deepanwayx** [comment]
That is correct. In MELD, the mapping is

`label index mapping = {'neutral': 0, 'surprise': 1, 'fear': 2, 'sadness': 3, 'joy': 4, 'disgust': 5, 'anger':6}`

 The mapping in `dataloader.py` has now been fixed.
